FROM nginx:latest
MAINTAINER ccchenyihao "chenyihao17@qq.com"
RUN /bin/bash -c 'echo -e "deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib\ndeb http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib\ndeb-src http://mirrors.aliyun.com/debian/ jessie main non-free contrib\ndeb-src http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib">/etc/apt/sources.list'
RUN apt-get update
# http://stackoverflow.com/questions/32145650/how-to-set-mysql-username-in-dockerfile
# RUN apt-get install -f -y mysql-server mysql-client 
RUN apt-get install -f -y nginx
RUN apt-get install -f -y php5 php5-json php5-fpm php5-mysql php5-curl php5-gd php5-cli php5-common
RUN apt-get install -f -y git
RUN sed -i 's/\s(sendfile.*)/ sendfile off;/' /etc/nginx/nginx.conf
RUN sed -i 's/^(display_errors.*)/display_errors = On/' /etc/php5/fpm/php.ini
RUN sed -i "s/^}$/location ~ \\\.php$ {\\n        fastcgi_pass unix:\/var\/run\/php5-fpm.sock;\\n        fastcgi_index index.php;\\n        include fastcgi_params;\\n        }\\n}/" /etc/nginx/conf.d/default.conf
RUN sed -i 's/index  /index  index.php /' /etc/nginx/conf.d/default.conf
RUN sed -i '1i\daemon  off;' /etc/nginx/nginx.conf
CMD service php5-fpm start
# RUN service php5-fpm reload
CMD nginx &
#USER nginx #todo


EXPOSE 80 443 3306

# docker build -t 'chan17_nginx_php5_dev_env' .
# docker run -d -p 80:62201 -t -i --name test_nginx1 -v /vagrant/code:/usr/share/nginx/html -v $PWD/conf/nginx.conf:/etc/nginx/nginx.conf nginx /bin/bash 
# docker run -d -p 62201:80 -t -i --name test_nginx2 -v /vagrant/code:/usr/share/nginx/html chan17_nginx_php5_dev_env /bin/bash 